### PR TITLE
cudatoolkit + torchvision to env

### PR DESCRIPTION
**Pull request by frcaud**

### CODE REVIEW

**Comment by agramfort** [comment]
@frcaud you copied the env from folicule?

**Comment by frcaud** [comment]
part of it, I wanted to add cudatoolkit

**Comment by agramfort** [comment]
@frcaud @tomMoral 

in https://github.com/ramp-kits/stroke_lesions/runs/5478508350?check_suite_focus=true

```
Pip subprocess error:
[1000](https://github.com/ramp-kits/stroke_lesions/runs/5478508350?check_suite_focus=true#step:5:1000)
  Running command git clone --filter=blob:none --quiet https://github.com/paris-saclay-cds/ramp-workflow /tmp/pip-req-build-fy0exobb
[1001](https://github.com/ramp-kits/stroke_lesions/runs/5478508350?check_suite_focus=true#step:5:1001)
  Running command git clone --filter=blob:none --quiet https://github.com/AlexandreHutton/stroke /tmp/pip-req-build-sp29sq7r
[1002](https://github.com/ramp-kits/stroke_lesions/runs/5478508350?check_suite_focus=true#step:5:1002)
ERROR: Could not find a version that satisfies the requirement tensorflow-addons<0.12 (from versions: 0.13.0, 0.14.0, 0.15.0, 0.16.1)
[1003](https://github.com/ramp-kits/stroke_lesions/runs/5478508350?check_suite_focus=true#step:5:1003)
Installing pip dependencies: ...working... Ran pip subprocess with arguments:
[1004](https://github.com/ramp-kits/stroke_lesions/runs/5478508350?check_suite_focus=true#step:5:1004)
ERROR: No matching distribution found for tensorflow-addons<0.12
```

**Comment by tomMoral** [comment]
Fixed in the follow up pushed by removing version pin: https://github.com/ramp-kits/stroke_lesions/runs/5478567245?check_suite_focus=true
=

**Comment by agramfort** [comment]
victory ! 

thx @tomMoral !

**Comment by frcaud** [comment]
thanks @tomMoral !

**Pull request merged**
